foundations: ["src/core/foundations"]
svgs: ["src/core/svgs"]
accordion: ["src/core/components/accordion"]
button: ["src/core/components/button"]
checkbox: ["src/core/components/checkbox"]
choice card: ["src/core/components/choice-card"]
grid: ["src/core/components/grid"]
link: ["src/core/components/link"]
radio: ["src/core/components/radio"]
text input: ["src/core/components/text-input"]
