foundations: ["src/core/foundations"]
svgs: ["src/core/svgs"]
button: ["src/core/components/button"]
checkbox: ["src/core/components/checkbox"]
grid: ["src/core/components/grid"]
link: ["src/core/components/link"]
radio: ["src/core/components/radio"]
text input: ["src/core/components/text-input"]
