brand: ["src/core/brand"]
foundations: ["src/core/foundations"]
icons: ["src/core/icons"]
accordion: ["src/core/components/accordion"]
button: ["src/core/components/button"]
checkbox: ["src/core/components/checkbox"]
choice card: ["src/core/components/choice-card"]
footer: ["src/core/components/footer"]
grid: ["src/core/components/grid"]
link: ["src/core/components/link"]
radio: ["src/core/components/radio"]
select: ["src/core/components/select"]
text area: ["src/core/components/text-area"]
text input: ["src/core/components/text-input"]
user feedback: ["src/core/components/user-feedback"]
